apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-cluster-role
rules:
 - apiGroups: ["argoproj.io"]
   resources: ["sensors", "gateways"]
   verbs: ["get", "list", "watch", "update", "patch", "create"]
 - apiGroups: ["argoproj.io"]
   resources: ["workflows"]
   verbs: ["create", "delete"]
 - apiGroups: ["", "batch", "apps"]
   resources: ["configmaps", "secrets", "pods", "services", "jobs", "deployments", "events"]
   verbs: ["get", "watch", "list", "update", "patch", "create"]
